# Generated by Django 5.0.6 on 2024-08-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_comment_cart_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
