# Generated by Django 5.0.6 on 2024-08-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
